version: '2.4'
volumes:
  zigbee2mqtt-data:
services:
  zigbee2mqtt:
    build:
      context: .
    restart: always
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - zigbee2mqtt-data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
